name: LocalStack Setup

on:
  workflow_call:

jobs:
  start-localstack:
    name: Start LocalStack
    runs-on: ubuntu-latest
    outputs:
      access_key_id: ${{ steps.set-creds.outputs.access_key_id }}
      secret_access_key: ${{ steps.set-creds.outputs.secret_access_key }}
      region: ${{ steps.set-creds.outputs.region }}

    services:
      localstack:
        image: localstack/localstack:3
        ports:
          - 4566:4566
        env:
          SERVICES: s3,iam
          DEBUG: 1
          DATA_DIR: /tmp/localstack/data
        options: >-
          --health-cmd "curl -f http://localhost:4566/_localstack/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set environment variables for LocalStack
        id: set-creds
        run: |
          echo "LOCALSTACK_AWS_ACCESS_KEY_ID=test" >> $GITHUB_OUTPUT
          echo "LOCALSTACK_AWS_SECRET_ACCESS_KEY=test" >> $GITHUB_OUTPUT
          echo "LOCALSTACK_AWS_REGION=us-east-1" >> $GITHUB_OUTPUT
